language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t portillaj/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true portillaj/react-test npm test -- --coverage

after_success:
  - docker build -t portillaj/multi-client ./client
  - docker build -t portillaj/multi-nginx ./nginx
  - docker build -t portillaj/multi-server ./server
  - docker build -t portillaj/multi-worker ./worker

  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take those images and push them to docker hub
  - docker push portillaj/multi-client
  - docker push portillaj/multi-nginx
  - docker push portillaj/multi-server
  - docker push portillaj/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-1-165814455275
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
