language=generic
sudo: required
services:
  -docker

before_install:
  - docker build -t jasonportilla/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true jasonportilla/react-test npm test -- --coverage

after_success:
  - docker build -t jasonportilla/multi-client ./client
  - docker build -t jasonportilla/multi-nginx ./nginx
  - docker build -t jasonportilla/multi-server ./server
  - docker build -t jasonportilla/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push jasonportilla/multi-client
  - docker push jasonportilla/multi-nginx
  - docker push jasonportilla/multi-server
  - docker push jasonportilla/multi-worker