language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jasonportilla/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true jasonportilla/react-test npm test -- --coverage

after_success:
  - docker build -t jasonportilla/dockerhub:multi-client ./client
  - docker build -t jasonportilla/dockerhub:multi-nginx ./nginx
  - docker build -t jasonportilla/dockerhub:multi-server ./server
  - docker build -t jasonportilla/dockerhub:multi-worker ./worker

  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take those images and push them to docker hub
  - docker push jasonportilla/dockerhub:multi-client
  - docker push jasonportilla/dockerhub:multi-nginx
  - docker push jasonportilla/dockerhub:multi-server
  - docker push jasonportilla/dockerhub:multi-worker